sudo: required

language: cpp

services:
  - docker

jobs:
  include:
    - script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git debian:jessie /bin/bash -c '
        export PS4='\''+ \e[33;1m($0 @ line $LINENO) \$\e[0m '\'' # quotes must be escaped
        set -e
        set -x
        apt update
        apt install -y git cmake g\+\+-4.8 ninja-build cmake
        BUILDDIR=$(mktemp -d)
        cd ${BUILDDIR}
        cmake -G Ninja -DCMAKE_C_COMPILER=gcc-4.8 -DCMAKE_CXX_COMPILER=g++-4.8 /repo.git
        cd -
        cmake --build ${BUILDDIR} '
    - script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git debian:stretch /bin/bash -c '
        export PS4='\''+ \e[33;1m($0 @ line $LINENO) \$\e[0m '\'' # quotes must be escaped
        set -e
        set -x
        apt update
        apt install -y git cmake g\+\+-6 ninja-build cmake
        BUILDDIR=$(mktemp -d)
        cd ${BUILDDIR}
        cmake -G Ninja -DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6 /repo.git
        cd -
        cmake --build ${BUILDDIR} '
    - script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/repo.git --entrypoint='/bin/bash' gitlab-registry.cern.ch/ci-tools/ci-worker:cc7 -c '
        export PS4='\''+ \e[33;1m($0 @ line $LINENO) \$\e[0m '\'' # quotes must be escaped
        set -e
        set -x
        yum install -y glibc-headers glibc-devel make gcc-c++ gcc binutils ninja-build
        BUILDDIR=$(mktemp -d)
        cd ${BUILDDIR}
        cmake -G Ninja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ /repo.git
        cd -
        cmake --build ${BUILDDIR} '
